# Site Settings



# jekyll-paginate configuration
paginate: 5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
baseurl: "http://www.gchure.github.io/"
# Customise feed settings (uncommenting following two fields to customise feed title and description)
title:		     "Griffin Chure"
# description:	     "a minimalist Jekyll theme-Custom"
