# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ""

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'CV', folder: 'cv', file: 'cv.html'}
- {name: 'Research', folder: 'research', file: 'research.html'}
- {name: 'Teaching', folder: 'teaching', file: 'Teaching.html'}
# - {name: 'Writing', folder: 'pages', file: 'documentation.html'}
# - {name: 'Photography', folder: 'pages', file: 'about.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/gdchure'}
- {icon: 'instagram', link: 'https://instagram.com/gchure'}
- {icon: 'github', link: 'https://github.com/gchure'}
- {icon: 'envelope', link: 'mailto:gchure@caltech.edu'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy...'

# post_date_prefix: 'Written on'
